name: Build and deploy Hugo site
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      
      - name: Build
        run: hugo --minify
      
      - name: SFTP Deploy
        run: apt-get update && apt-get install -y sshpass
        run: echo 'put -r public/*' | sshpass -p ${{ secrets.SFTP_PASSWORD }} sftp ${{ secrets.SFTP_USERNAME }}@sftp.fourtythree.org:/public/sites/www.fourtythree.org
